### ISSUE TITLE
Duplicate modules

### ISSUE THREAD

**Issue by klieret** [hsf-training/training-center#80]
![image](https://github.com/hsf-training/training-center/assets/13602468/1f74f011-99f7-434e-a14d-461934e3f628)

**Comment by klieret** [comment]
It's not duplicate in the data file, so not sure what causes this

**Comment by ariostas** [comment]
It happens for the ones that don't have a `level` field set. Also, if you filter by only `beginner` or `advanced` this doesn't happen. So it's most likely an issue with the level filter.

**Comment by klieret** [comment]
I'm just gonna `git bisect` this later on, but that sounds like it was when we introduced the levels (my guess is that it's the correct number of modules that is shown, so somewhere some `map` or so maps to the wrong information). Because when you search for `shell`, we exactly miss the `SSH` module , which is probably replaced by a duplicate `shell`

**Comment by ariostas** [comment]
In your original post the `SSH` module is not showing up because it's in alpha. I think it's not replacing other modules, it's just duplicating the ones that don't have a level specified.

It also happens when a tutorial the level includes both beginner and advanced as for the C++ course.

The issue is with this code:
https://github.com/hsf-training/training-center/blob/dbe31c2c1174231f4beb53d81a8d68ab467bfc5d/src/components/filters.js#L115-L120

The inner loop can return the tutorial multiple times when the level is undefined or when the tutorial and the query include multiple matching levels.

This will also be an issue with some of the other filters, but it should be pretty easy to solve by adding an extra line to remove duplicates
